name: RSS Everyday
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
#env:
#  TZ: Asia/Shanghai

jobs:
  search-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: build
      run: go run main.go -tg-bot=${{secrets.BOTTOKEN}} -tg-channel=${{secrets.CHANNELID}} -goroutine-num 10
    - name: Commit Files
      run: |
        git config --local user.email "youguanxinqing@qq.com"
        git config --local user.name "youguanxinqing(bot)"
        git diff-index --quiet HEAD || git commit -m "update digest $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.INDEX_ACTION_TOKEN}}